### ISSUE TITLE
希望加入固定引导音频的功能

### ISSUE THREAD

**Issue by ocetars** [idranme/koishi-plugin-fish-speech-online#1]
使用时发现合成语音在不同的引导音频下差异过大。希望能在某些表现满意的时候，能手动固定选用此时的引导音频而不再随机变化

**Comment by idranme** [comment]
你要习惯抽卡（

**Comment by ocetars** [comment]
> 你要习惯抽卡（

😖

**Comment by Ocetars** [comment]
新出现了无限重启问题，不知道是bug还是其他原因？使用fs-tts指令生成任意内容都会自动重启koishi @idranme
