### ISSUE TITLE
频繁出现“语音生成失败”问题

### ISSUE THREAD

**Issue by ocetars** [idranme/koishi-plugin-fish-speech-online#2]
该情况已出现近一周时间，表现为随机出现此问题，如下两图，图二是该问题的出现频率。日志无log信息
![Screenshot_2024-05-31-12-49-04-150_com.tencent.mobileqq.jpg](https://github.com/idranme/koishi-plugin-fish-speech-online/assets/74854972/ab6f6d94-1d7a-439c-9cc1-df9f34ee7186)

![Screenshot_2024-05-31-12-52-17-144_com.tencent.mobileqq.jpg](https://github.com/idranme/koishi-plugin-fish-speech-online/assets/74854972/aef6d1a2-3a02-431a-8705-b96f3e85935a)

**Comment by ocetars** [comment]
也许可以让程序在生成失败时尝试重新生成?

**Comment by idranme** [comment]
> 也许可以让程序在生成失败时尝试重新生成?

最新版已增加此功能。
