### ISSUE TITLE
参数中的speaker设置找到对应的人太难

### ISSUE THREAD

**Issue by yjc1314** [idranme/koishi-plugin-fish-speech-online#3]
![image](https://github.com/idranme/koishi-plugin-fish-speech-online/assets/47632559/fb362ea3-5f9e-49e4-ae9f-9fb9acdcea8a)

能否加一个模糊搜索，可以快速切换这个选项

**Comment by idranme** [comment]
可以直接点击下拉菜单输入关键词搜索

**Comment by yjc1314** [comment]
> 可以直接点击下拉菜单输入关键词搜索

![image](https://github.com/user-attachments/assets/4617520d-8ade-4373-9ae8-9653499def73)
可能问题说得不是很准确是，模糊搜索失效

**Comment by idranme** [comment]
这个应该是 koishi 的 bug，建议前往 koishi 仓库反馈。
